// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgb4AACIf19WVIpxVLrcne_uOQv1HnfmY',
    appId: '1:779599136804:web:e4f9048ba0591ef555f0b1',
    messagingSenderId: '779599136804',
    projectId: 'flutter-sribbu-smart',
    authDomain: 'flutter-sribbu-smart.firebaseapp.com',
    storageBucket: 'flutter-sribbu-smart.firebasestorage.app',
    measurementId: 'G-RL73XXJWLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXc4lVO9OU0hbUnq0bWg8Ky-gvidVoQQY',
    appId: '1:779599136804:android:a75dbf6952a202d055f0b1',
    messagingSenderId: '779599136804',
    projectId: 'flutter-sribbu-smart',
    storageBucket: 'flutter-sribbu-smart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD91AjnkOyl5uBgOaOL8bWQlBO3LTM3AEw',
    appId: '1:779599136804:ios:43efcb446df7bd6955f0b1',
    messagingSenderId: '779599136804',
    projectId: 'flutter-sribbu-smart',
    storageBucket: 'flutter-sribbu-smart.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD91AjnkOyl5uBgOaOL8bWQlBO3LTM3AEw',
    appId: '1:779599136804:ios:43efcb446df7bd6955f0b1',
    messagingSenderId: '779599136804',
    projectId: 'flutter-sribbu-smart',
    storageBucket: 'flutter-sribbu-smart.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgb4AACIf19WVIpxVLrcne_uOQv1HnfmY',
    appId: '1:779599136804:web:b0d33b9d25bf631755f0b1',
    messagingSenderId: '779599136804',
    projectId: 'flutter-sribbu-smart',
    authDomain: 'flutter-sribbu-smart.firebaseapp.com',
    storageBucket: 'flutter-sribbu-smart.firebasestorage.app',
    measurementId: 'G-PTC1Z1RT4G',
  );
}
